title: fefanto
name: Fefanto - github personal page


gems:
  - github-pages
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-sass-converter
 #from garthdb-----
  #- jekyll-seo-tag
  #- jekyll-feed
  #-----------------



sass:
  sass_dir: _sass
  style: compressed




#baseurl: "/"
#from garthdb-----
#baseurl: 
#url: http://www.fefanto.com






permalink: "/blog/:categories/:title.html"

exclude: [node_modules, gulpfile.js,css/style.scss.orig]


# Where are tags and categories displayed
tag_page: '/blog/tags.html'
category_page: '/blog/categories.html'

#TBD
paginate: 10
paginate_path: '/blog/page:num'


disqus_short_name: 'fefanto'
latest_post_count: 3


#from garthdb----
#future: true
markdown: kramdown
#highlighter: rouge
#kramdown:
#  input: GFM
#  syntax_highlighter: rouge
#   syntax_highlighter_opts:
#    css_class: highlight
#    span:
#      line_numbers: false
#    block:
#      line_numbers: true
#      start_line: 1
#-----------

#from garthdb----
#timezone: UTC
#collections:
#  posts:
#    title: Posts
#    output: true
#  uploads:
#    title: Uploads
#    output: true
#-----------




