title: fefanto
name: Fefanto - github personal page
#baseurl: "/"

gems:
  - jekyll-paginate
  - jekyll-sitemap


markdown: kramdown


permalink: pretty

exclude: [node_modules, gulpfile.js, wireframe]


# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

#TBD
paginate: 2
paginate_path: '/blog/page:num'


disqus_short_name: 'fefanto'
